version: '3.7'

services:
    web:
        build: .
        depends_on:
            - postgres
        links:
            - "postgres:postgres"
        volumes:
            - .:/shortyurl
        env_file: .env
        environment:
            - MODE
            - POSTGRES_HOST=postgres
        ports:
            - "8000:8000"
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000

    postgres:
        restart: always
        image: postgres:latest
        env_file: .env
        volumes:
        - /var/lib/postgresql
        ports:
        - "5432:5432"
