version: '3.7'

services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        command: python app/main.py
        volumes:
            - ./backend:/app
        env_file: ./backend/.env
        environment:
            PYTHONPATH: .
        depends_on:
            - postgres

    postgres:
        restart: always
        image: postgres:latest
        env_file: ./backend/.env
        volumes:
        - /var/lib/postgresql
        ports:
        - "5432:5432"
